spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/scan
    username: postgres
    password: ****

ping:
  timeout: 500

cors:
  frontUrl: http://127.0.0.1:5500